version: '3.3'
services:
  dockergui:
    build: ./ui-for-docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    command: uifd/ui-for-docker
  ssmdb2:
    image: biarms/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ssmdb2'
      MYSQL_USER: 'otto'
      MYSQL_PASSWORD: 'otto'
      MYSQL_ROOT_PASSWORD: 'mc4hct'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  ssmdb2_myadmin:
    image: ebspace/armhf-phpmyadmin
    ports:
      - '8088:80'
    links:
      - ssmdb2
    environment:
      PMA_HOST: 'ssmdb2'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
  cronmaster:
    image: alpine:3.8
    volumes:
      - ./cronmaster:/usr/local
    command: /usr/local/startup.sh
  stream0:
    restart: unless-stopped
    image: patsoffice/mjpg-streamer
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8090:8080
    command: mjpg_streamer -i 'input_uvc.so -d /dev/video0 -r 1280x720 -f 1' -o 'output_http.so -w /usr/local/share/mjpg-streamer/www'

# Names our volume
volumes:
  my-db: