version: '3.3'
services:
  ssmdb2:
    image: biarms/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ssmdb2'
      MYSQL_USER: 'otto'
      MYSQL_PASSWORD: 'otto'
      MYSQL_ROOT_PASSWORD: 'mc4hct'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  ssmdb2_myadmin:
    image: ebspace/armhf-phpmyadmin
    ports:
      - '8088:80'
    links:
      - ssmdb2
    environment:
      PMA_HOST: 'ssmdb2'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
  cronmaster2:
    image: alpine:3.8
    volumes:
      - ./cronmaster:/usr/local
    command: /usr/local/startup.sh
  stream0:
    restart: always
    image: patsoffice/mjpg-streamer
    devices:
      - /dev/video0:/dev/video0
    environment: 
      MJPEG_STREAMER_INPUT: '-y -n -r 1280x720 -f 30 -yuv'
    ports:
      - 8090:8080
    command: mjpg_streamer -i 'input_uvc.so -d /dev/video0 -f 30' -o 'output_http.so -w /usr/local/share/mjpg-streamer/www'

# Names our volume
volumes:
  my-db: