# create databases
CREATE DATABASE IF NOT EXISTS `MEYSHOT`;
CREATE DATABASE IF NOT EXISTS `SSMDB2`;

# create tables
CREATE TABLE `MEYSHOT`.`Upload` ( `Uploaddatum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`Uploaddatum`)) ENGINE = InnoDB;
CREATE TABLE `MEYSHOT`.`Infoticker` ( `ID` INT NOT NULL AUTO_INCREMENT , `Startdatum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `Enddatum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `Titel` TEXT NOT NULL , `Text` TEXT NOT NULL , `Ersteller` TEXT NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `MEYSHOT`.`User` ( `ID` INT NOT NULL AUTO_INCREMENT , `Username` VARCHAR(40) NOT NULL , `Name` VARCHAR(40) NOT NULL , `Pass` BINARY(64) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `MEYSHOT`.`Aufsichten` ( `ID` INT NOT NULL AUTO_INCREMENT , `User` INT NOT NULL , `Anfang` DATETIME NOT NULL , `Ende` DATETIME NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;

# create root user and grant rights
CREATE USER 'otto'@'%' IDENTIFIED BY 'otto';
GRANT ALL PRIVILEGES ON *.* TO 'otto'@'%';

# set timezone
SET GLOBAL time_zone = 'Europe/Berlin';